language: go

go_import_path: github.com/shoebox/dothething

go:
  - 1.14.x

before_install:
  - go get -t -v ./...

install:
  - export PATH=$PATH:$HOME/gopath/bin
  - go get -v -t ./...

script:
  - go test ./... -tags mock -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

